# -*- coding: utf-8 -*-
"""coins.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1677a8FNuUbuzGFG59sv_DD2H1XY6zeoY
"""

#g2g
print("Please enter the amount of money to convert:")

#g2g
print("# of dollars:")
dollars = int(input()) * 100

#g2g
print("# of cents:")
cents = int(input())

#needs work
total = dollars + cents
maxquarters = total // 25
afterquarters = total % 25
dimes = afterquarters // 10
afterdimes = afterquarters % 10
nickels = afterdimes // 5
afternickels = afterdimes % 5
pennies = afternickels // 1

###final output
print("The coins are", quarters,"quarters,", dimes, "dimes,", nickels,"nickels and", pennies, "pennies")