# -*- coding: utf-8 -*-
"""counter

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xf4o1mLMH53nY8PqwcXKxqj6oOf32274
"""

# Counts value of coins and converts to dollars

print("Please enter number of quarters:")
quarters = int(input())
total_quarters = quarters *25

print("Please enter number of dimes:")
dimes = int(input())
total_dimes = dimes * 10

print("Please enter number of nickels:")
nickels = int(input())
total_nickels = nickels *5

print("Please enter number of pennies:")
pennies = int(input())
total_pennies = pennies *1

total = total_quarters + total_dimes +total_nickels +total_pennies

dollars = total // 100
cents = total % 100

print("The total is", dollars, "dollars and", cents, "cents")